include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = ggpokerbypassprefs

ggpokerbypassprefs_FILES = GGPRootListController.m
ggpokerbypassprefs_FRAMEWORKS = UIKit
ggpokerbypassprefs_PRIVATE_FRAMEWORKS = Preferences
ggpokerbypassprefs_CFLAGS = -fobjc-arc
ggpokerbypassprefs_INSTALL_PATH = /Library/PreferenceBundles

include $(THEOS_MAKE_PATH)/bundle.mk
